### ISSUE TITLE
Its not Working now

### ISSUE THREAD

**Issue by shiri999** [lwc-soql-builder/lwc-soql-builder#16]
![image](https://user-images.githubusercontent.com/102269500/159823594-dab713aa-f153-442f-b08d-63dfbdbd5626.png)

I love this tool, but unfortunately recently I am facing with the issue "Cannot read properties of undefined (reading 'map')"

**Comment by atskimura** [comment]
@shiri999 Thanks for using. Could you post the information that appears when you click on "Show Details"?

**Comment by shiri999** [comment]
That was quick response..

{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'map')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'map')\n    at je.storeChange (https://lwc-soql-builder.github.io/lwc-soql-builder/app.js?__WB_REVISION__=a011bb6c66bf2cdf2b8b97beeb557d95:1:30494)\n    at https://lwc-soql-builder.github.io/lwc-soql-builder/0.app.js:9:30766\n    at Fa (https://lwc-soql-builder.github.io/lwc-soql-builder/0.app.js:9:30011)\n    at ie.dataCallback (https://lwc-soql-builder.github.io/lwc-soql-builder/0.app.js:9:30743)\n    at e (https://lwc-soql-builder.github.io/lwc-soql-builder/app.js?__WB_REVISION__=a011bb6c66bf2cdf2b8b97beeb557d95:1:15614)\n    at y (https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js?__WB_REVISION__=d45abe68a385d407e937d10e2cc5ae54:17:102662)\n    at https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js?__WB_REVISION__=d45abe68a385d407e937d10e2cc5ae54:17:262218\n    at dispatch (https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js?__WB_REVISION__=d45abe68a385d407e937d10e2cc5ae54:17:105942)\n    at https://lwc-soql-builder.github.io/lwc-soql-builder/app.js?__WB_REVISION__=a011bb6c66bf2cdf2b8b97beeb557d95:1:16047\n    at https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js?__WB_REVISION__=d45abe68a385d407e937d10e2cc5ae54:19:3016"
}

**Comment by atskimura** [comment]
@shiri999 I cannot reproduce it and cannot seem to find the cause immediately. Is it occurring only in one particular organization?

**Comment by shiri999** [comment]
I am very surprised why it stopped working, does not work either with
Sandbox or Prod org.

however, it works at times, but just for a few seconds only,   it worked
today for a few secs...
