### ISSUE TITLE
Sandboxログイン時にエラーが発生しました。[Error] UNSUPPORTED_API_VERSION: Invalid Api version specified on URL

### ISSUE THREAD

**Issue by mcho71** [lwc-soql-builder/lwc-soql-builder#30]
##  概要

Sandboxへログインする際にエラーが発生しました。

```
sf:UNSUPPORTED_API_VERSION: UNSUPPORTED_API_VERSION: Invalid Api version specified on URL
    at a.getError (https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:17:96123)
    at https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:17:94479
    at https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:19:3016
    at https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:19:3044
    at MutationObserver.s (https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:17:176951)
    at t.$$lwcObserverCallbackWrapper$$ (https://lwc-soql-builder.github.io/lwc-soql-builder/2.app.js:17:294805)
_loginCallback @ app.js:1
```

## 一時的な対処

セッションストレージの`lsb.apiVersion`を`58.0`から`56.0`に変更したところ、エラーとならずに動きました。

<img width="682" alt="image" src="https://github.com/lwc-soql-builder/lwc-soql-builder/assets/30787346/2c700f21-417a-469c-93e2-cde38b6e5c2e">

**Comment by atskimura** [comment]
報告ありがとうございます。
一回APIバージョンをセッションストレージにセットしたら再取得しないコードになってしまっていました。
そのためセッションストレージが空の状態でSummer '23の組織に接続してから、別のSpring '23の組織に接続すると、この現象が発生しました。
ログイン時にAPIバージョンを再取得するようにするのが正解でした。どこかのタイミングで修正したいと思います。
